customer_forms/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LoginView, LogoutView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("login/", LoginView.as_view(template_name="forms/login_form.html"), name="login"),
    path("logout/", LogoutView.as_view(template_name="forms/loggedout.html"),name="logout"),
    path("", include("forms.urls")),
]

forms/urls.py
from django.urls import path
from .views import static_views, customer_views, document_views

app_name = "forms"
urlpatterns = [
    path("", static_views.index, name="index"),
    # Customer
    path("register/", customer_views.CustomerCreate.as_view(), name="register"),
    path("update/<str:pk>", customer_views.UpdateCustomer.as_view(), name="cust-update"),
    path("delete/<str:pk>", customer_views.DeleteCustomer.as_view(), name="cust-del"),
    path("cust-id/", customer_views.CustomerId.as_view(), name="cust-id"),
    path("thankyou/", static_views.thank_you, name="thank_you"),
    # Staff
    path("home/", static_views.user_home, name="user-home"),
    path("download/", document_views.DownloadDocument.as_view(), name="download"),
    path("upload/", document_views.CreateDocument.as_view(), name="upload"),
]

forms/admin.py
from django.contrib import admin
from . import models

# Register your models here.

admin.site.register(models.Customer)
admin.site.register(models.Document)

forms/apps.py
from django.apps import AppConfig


class FormsConfig(AppConfig):
    name = "forms"

forms/forms.py
from django.forms.fields import CharField, ChoiceField
from .models import Customer, Document
from django.forms import Form, ModelForm, ModelMultipleChoiceField, widgets
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError


# avaliable fields are
# comp_name, street1, street2, city, state, post_code, country, phone_number
class CustomerForm(ModelForm):
    class Meta:
        model = Customer
        exclude = ("entry_date", "last_modified", "email_hash")

class LoginForm(ModelForm):
    """Simple login form"""
    class Meta:
        model = User
        fields = ("username", "password")


class GenerateDocumentForm(Form):
    document = ModelMultipleChoiceField(queryset=Document.objects.all())
    customer = ModelMultipleChoiceField(queryset=Customer.objects.all())

    def clean_document(self):
        data = self.cleaned_data["document"]
        if len(data) > 1:
            raise ValidationError("Can only procress one document at a time.")
        return data


class DocumentForm(ModelForm):
    class Meta:
        model = Document
        exclude = ("last_modified",)


ACTIONS = (("Update", "1"), ("Delete", "2"))


class CustomerIdForm(Form):
    email_address = CharField(max_length=254)
    action = ChoiceField(choices=ACTIONS)

    def clean(self):
        cd = self.cleaned_data
        pk = cd.get("email_address")
        action = cd.get("action")
        if not Customer.objects.filter(email_address=pk):  # nothing found
            raise ValidationError("Email address matches no customer record")
        else:
            return cd

forms/helper_functions.py
import gettext
import pycountry
import requests
from bs4 import BeautifulSoup
import re
from cleanco import cleanco
from hashlib import sha256


def hash(email_address):
    """Generates an unique identifier for a given item."""
    # hash based on email_address
    return sha256(str(email_address).encode('utf-8')).hexdigest()


def english_to_katakana(word):
    """ converts english into katakana - works with more than one words;
    english_to_katakana("good morning") -> 'グッド・モーニング' """
    url = 'https://www.sljfaq.org/cgi/e2k_ja.cgi'
    url_q = url + '?word=' + word
    headers = {'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1.1 Safari/605.1.15'}
    request = requests.get(url_q, headers=headers)
    soup = BeautifulSoup(request.text, 'html.parser')
    katakana_string = soup.find_all(class_='katakana-string')[0].string.replace('\n', '')
    return katakana_string

def to_jap_com_name(comnam):
    ''' extract suffix, convert name to katakana, translate suffix - return string
    to_jap_com_name('Padilla PLC') => 'パディラー株式会社' '''
    # 1. extract company suffix
    # 2. Katakana name
    # 3. Append Translation of suffix
    analyzed_name = cleanco(comnam)
    basename, suffix = analyzed_name.clean_name(), analyzed_name.type()
    jap_basename = english_to_katakana(basename)
    jap_suffix = '株式会社' if suffix else ''
    return jap_basename + jap_suffix
    

def to_jap_country(eng_country):
    translator = gettext.translation('iso3166', pycountry.LOCALES_DIR, languages=["ja"])
    translator.install()
    _ = translator.gettext
    jap_country=_(eng_country)
    return jap_country if jap_country!=eng_country else None

def extract_street_num(street1):
    '''picks up any numbers before the text
    Japanese address put these are end of line'''
    match = re.match("(?P<num>\s*\d+-?\d*)?\s*(?P<rem>.*)",street1,flags=re.DOTALL)
    return match.group("num"), match.group("rem")

forms/views/customer_views.py
from django.http.response import HttpResponseRedirect
from django.shortcuts import get_object_or_404, redirect, render
from django.views.generic.edit import CreateView
from django.views.generic import View

from .. import models, forms


# Create new Customer
class CustomerCreate(CreateView):
    model = models.Customer
    form_class = forms.CustomerForm



class CustomerId(View):
    '''
    Identify customer via email_address
    redirect to update or delete page with customer information
    '''
    template_name = "forms/customer_id_form.html"
    form_class = forms.CustomerIdForm

    def get(self, request, *args, **kwargs):
        form = self.form_class
        return render(request, self.template_name, {'form': form})

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            email_address = request.POST["email_address"]
            customer = models.Customer.objects.get(email_address=email_address)
            customer_pk = customer.email_hash
            action = request.POST["action"]
            print(action)
            if action == "Update":
                return redirect("forms:cust-update", pk=customer_pk)
            elif action == "Delete":
                return redirect("forms:cust-del", pk=customer_pk)

        return render(request, self.template_name, {'form': form}) 


class UpdateCustomer(View):
    """
    Form to update customer information - email_address field cannot be changed
    """
    template_name = "forms/customer_form.html"
    form_class = forms.CustomerForm

    def get(self, request, pk:str, *args, **kwargs) -> HttpResponseRedirect:
        form = self.form_class
        instance = get_object_or_404(models.Customer, pk=pk)
        email_address = instance.email_address
        return render(request, self.template_name, {'form': form,'email_address':email_address})
    
    def post(self, request, *args, **kwargs):
        email_address = request.POST.get("email_address")
        instance = get_object_or_404(models.Customer, email_address=email_address)
        form = self.form_class(request.POST or None, instance=instance)
        if form.is_valid():
            form.save()
            return redirect("forms:index")
        return render(request, self.template_name, {'form': form,'email_address':email_address})


class DeleteCustomer(View):
    # need to confirm that instance is deleted
    def get(self, request, pk:str, *args, **kwargs) -> HttpResponseRedirect:
        if instance:= models.Customer.objects.get(pk=pk):
            instance.delete()
            return redirect('forms:index')
        # return some kind of error
    

forms/views/document_views.py
from django.http.request import QueryDict
from django.http.response import Http404
from django.shortcuts import redirect, render
from django.http import HttpResponse, HttpResponse
from django.views.generic import View
from django.conf import settings
from django.contrib.auth.mixins import LoginRequiredMixin

import re
from urllib.parse import quote

from .. import models, forms


TEMPLATE_ERROR_MESSAGE = "There was a problem uploading your template. Please check your information and try again."

class CreateDocument(LoginRequiredMixin, View):
    model = models.Document
    form_class = forms.DocumentForm
    template_name = "forms/document_form.html"
    context_dict = {"props": sorted(models.CUSTOMER_CHOOSABLE_PROPERTIES)}

    def get(self, request, *args, **kwargs):
        form = self.form_class
        return render(request, self.template_name, self.context_dict)

    def extract_mapping(self, q: QueryDict) -> str:
        """extracts mappings from form's post request
        mapping schema is  "('Cell',customer.attr);('Cell2',customer.attr2)" """
        is_mapping = lambda x: re.search("^(?:cell|val)\d+$", x)
        mapping_keys = filter(is_mapping, q.keys())
        # assert len(list(mapping_keys))%2 ==0, "Uneven number of cells and values" #this consumes the filter

        mapping = []
        for cell_key in mapping_keys:
            val_key = next(mapping_keys)  # iterating 2 at a time - will error out if uneven number
            assert self.is_valid_mapping(cell_key,val_key,q),"Mapping is not valid"
            cell, val = q[cell_key], q[val_key]
            entry = f"('{cell}',customer.{val})"
            mapping.append(entry)
        mapping = ";".join(mapping)
        assert mapping, "Mapping is empty"
        return mapping

    def is_valid_mapping(self,cell_key:str, val_key:str, q:QueryDict) -> bool:
        cell_match = re.search("^cell(?P<num>\d+)$",cell_key) 
        val_match = re.search(f"^val{cell_match['num']}$",val_key)
        if cell_match and val_match:
            cell, val = q[cell_key], q[val_key]
            is_cell_valid = re.search("^[A-Z]+\d+$",cell)
            is_val_valid = val in models.CUSTOMER_CHOOSABLE_PROPERTIES
            if is_cell_valid and is_val_valid: return True
        return False

    def post(self, request, *args, **kwargs):
        #this needs to be rethought
        # print("post requested")
        print(request.POST)
        try:
            mapping = self.extract_mapping(request.POST)
        except AssertionError as e:
            print("mapping failed")
            return render(request, self.template_name, self.context_dict) 

        try:
            new_document = models.Document(template=request.FILES["template"], mapping=mapping)
            new_document.save()
            print("new document successfully created")
            return redirect("forms:index")

        except:
            # new_context_dict = {'error': TEMPLATE_ERROR_MESSAGE}.update(self.context_dict)
            print("document creation failed")
            return render(request, self.template_name, self.context_dict)  # this is bugging out


from openpyxl import load_workbook
from zipfile import ZipFile
class DownloadDocument(LoginRequiredMixin, View):
    template_name = "forms/download_document.html"
    form_class = forms.GenerateDocumentForm

    def get(self, request, *args, **kwargs):
        form = self.form_class
        return render(request, self.template_name, {"form": form})

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            print(request.POST)
            document = models.Document.objects.get(pk=request.POST.get("document"))
            customers = [models.Customer.objects.get(pk=pk) for pk in request.POST.getlist("customer")]
            
            paths = []
            for customer in customers:
                paths.append(document.generate_document(customer))
            return self.download(paths)

        return render(request, self.template_name, {"form": form})

    def add_content_disposition_header(self, response, filename):
        """
        Add an RFC5987 / RFC6266 compliant Content-Disposition header to an
        HttpResponse to tell the browser to save the HTTP response to a file.
        """
        try:
            filename.encode('ascii')
            file_expr = 'filename="{}"'.format(filename)
        except UnicodeEncodeError:
            file_expr = "filename*=utf-8''{}".format(quote(filename))
        response['Content-Disposition'] = 'attachment; {}'.format(file_expr)
        return response

    
    def download(self,paths:list)-> HttpResponse:
        """
        return repsonse with zip of files
        """
        file_paths = map(lambda path: settings.MEDIA_ROOT / path, paths)
        checked_file_paths = list(filter(lambda path: path.exists(),file_paths))
        if len(checked_file_paths) == len(paths):
            zip_file_path = settings.MEDIA_ROOT / "generated/customer_data.zip"
            #build zip file
            with ZipFile(zip_file_path,'w') as zip: 
                for file in checked_file_paths: 
                    zip.write(file, file.name) 
                    file.unlink()
            #send reponse with zip file attached
            with open(zip_file_path, "rb") as to_download:
                response = HttpResponse(to_download.read(), content_type= "application/zip")
                response = self.add_content_disposition_header(response,zip_file_path.name)
                zip_file_path.unlink()
                return response
        raise Http404

forms/views/static_views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required



def index(request):
    """basic home page"""
    return render(request, "base.html")

def thank_you(request):
    """after registration page"""
    return render(request, "forms/thank_you.html")

@login_required
def user_home(request):
    """ user home_page after login"""
    return render(request, "forms/user_home.html")

forms/templates/forms/customer_id_form.html
{% extends 'base.html' %}


{% block content %}


<br>
<h1>Update/Delete</h1>

{% if form.errors %}
<p>{{ form.non_field_errors }}</p> 
<!-- can't get this to work  
https://stackoverflow.com/questions/22470637/django-show-validationerror-in-template -->

{% endif %}
    
<form method="post" action="">
    {% csrf_token %}
    <div class="form-group">
      <label for="email">Email Address</label>
      <input type="email" class="form-control" id="form.username" name="email_address" aria-describedby="emailHelp">
      <small id="emailHelp" class="form-text text-muted">Please enter the email you used when registering</small>
    </div>
    <div class="form-row">
        <div class="form-group col-1">
            <input type="submit" class="btn btn-primary" name="action" value="Update">
            <input type="hidden" name="next" value="{{ next }}">
        </div>
        <div class="form-group col-1">
            <input type="submit" class="btn btn-primary" name="action" value="Delete">
            <input type="hidden" name="next" value="{{ next }}">
        </div>
    </div>
  </form>
<br>
 <small class="form-text text-muted">To change email address, please delete current entry and resubmit a new one.</small>


{% endblock %}

<!-- have an update and a delete buttons -->

forms/templates/forms/document_form.html
{% extends 'base.html' %}


{% block content %}

<h1>Upload</h1>
<br>

{% if error %}
<small class="text-warning"> {{error}}</small>
{% endif %}
    
    <form method="POST" action="" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-group">
            <input type="file" name="template" required>
        </div>


        <div class="form-group">
            <p>Mapping:</p>
            <div id="rowContainer">
                <div class="form-row" >
                    <div class="col-6">
                        <label for="cell0">Cell</label>
                        <input class="form-control"  type="text" name="cell0" id="cell_template" placeholder="A1" required>
                    </div>
                    <div class="col-6" >
                        <label for="val0">Value </label>
                        <!-- <input type="text" name="val1" class="form-control"> -->
                        <select class="form-control" name="val0" id="val_template">
                            
                            {% for prop in props %}
                            <option value="{{prop}}">{{prop}}</option>
                            {% endfor %}
                                
                          </select>
                    </div>
                </div>
        
            </div>
        <a href="#" id="newRow" onclick="addRow()"><small>Add Row</small></a>

            <br><br>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
      





<script>
var rowNum = 0
const cell = document.getElementById("cell_template")
const val = document.getElementById("val_template")

function addRow(){    
    rowNum++
    var container = document.getElementById("rowContainer");
    var newMappingPair = createMapping();
    // var newMappingPair = document.createTextNode("Member " + (i+1))
    container.appendChild(newMappingPair);
    // container.appendChild(document.createElement("br"));
}

function createMapping(){
    // bootstrap class
    var row = document.createElement("div")
    row.className = "form-row"
    
    // Cell
    var col1 = document.createElement("div")
    col1.className = "col-6" 
    var new_cell = cell.cloneNode()
    new_cell.name = "cell" + rowNum
    col1.appendChild(new_cell)

    // Value
    var col2 = document.createElement("div")
    col2.className = "col-6" 
    var new_val = val.cloneNode(deep=true)
    new_val.name = "val" + rowNum
    col2.appendChild(new_val)
    
    row.appendChild(col1)
    row.appendChild(col2)
    return row
}
</script>



{% endblock %}

forms/templates/forms/download_document.html
{% extends "base.html" %}

{% block content %}

{% load widget_tweaks %}





<form method="post">
{% csrf_token %}

{% for hidden_field in form.hidden_fields %}
    {{ hidden_field }}
{% endfor %}

    
    
{% for field in form.visible_fields %}
<div class="form-group">
  {{ field.label_tag }}
  
  {% render_field field class="form-control" %}
  {% if field.help_text %}
    <small class="form-text text-muted">{{ field.help_text }}</small>
  {% endif %}
  {{field.errors}}
</div>
{% endfor %}

<button type="submit" class="btn btn-primary">Submit</button>
</form>

{% endblock %}

forms/templates/forms/loggedout.html
{% extends "base.html" %}

{% block content %}

<h1>Thank you</h1>
<p>これからも頑張ってください</p>

{% endblock %}

forms/templates/forms/login_form.html
{% extends "base.html" %}

{% block content %}

{% if form.errors %}
<p>Your username and password didn't match. Please try again.</p>
{% endif %}

{% if next %}
    {% if user.is_authenticated %}
    <p>Your account doesn't have access to this page. To proceed,
    please login with an account that has access.</p>
    {% else %}
    <p>Staff Only. Please login to access this page.</p>
    {% endif %}
{% endif %}


<br>
<form method="post" action="{% url 'login' %}">
    {% csrf_token %}
    <div class="form-group">
      <label for="username"> {{ form.username.label_tag }} </label>
      <input type="text" class="form-control" id="form.username" name="{{ form.username.html_name}}" aria-describedby="usernameHelp">
      <!-- <small id="usernameHelp" class="form-text text-muted">We'll never share your email with anyone else.</small> -->
    </div>
    <div class="form-group">
      <label for="password">{{ form.password.label_tag }}</label>
      <input type="password" class="form-control" id="form.password" name="{{ form.password.html_name}}">
    </div>
    <input type="submit" class="btn btn-primary" value="Submit">
    <input type="hidden" name="next" value="{{ next }}">
  </form>


{# Assumes you setup the password_reset view in your URLconf #}
{% comment %} <p><a href="{% url 'password_reset' %}">Lost password?</a></p> {% endcomment %}

{% endblock %}

forms/templates/forms/thank_you.html
{% extends 'base.html' %}

{% block content %}
<div class="jumbotron">
  <h1>
    Thank you for registering
  </h1>
  <p class="lead">We will process your order as quickly as possible </p>
</div>
{% endblock content %}

forms/templates/forms/user_home.html
{% extends 'base.html' %}

{% block content %}
<div class="jumbotron">
  <h1>
    <a class="text-dark" href="{% url 'forms:download' %}">Download Form</a>
  </h1>
  <a class="lead" href="{% url 'forms:upload' %}">Upload new template</a>
</div>

{% endblock %}